import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useRef } from "react";
import { CuboidCollider, RigidBody } from "@react-three/rapier";
import { LAMP } from "./constants";
import { Object3D } from "three";
export default function Lamp() {
    const target = useRef(new Object3D());
    return (_jsxs("group", { position: LAMP.POSITION, children: [_jsxs(RigidBody, { type: "fixed", colliders: false, children: [_jsx(CuboidCollider, { args: [0.5, 0.1, 0.5], position: [0, 0.1, 0] }), _jsxs("mesh", { castShadow: true, position: [0, 0.1, 0], children: [_jsx("cylinderGeometry", { args: [0.45, 0.55, 0.2, 24] }), _jsx("meshStandardMaterial", { color: "#1a1a1f", roughness: 0.3, metalness: 0.7 })] })] }), _jsxs("mesh", { castShadow: true, position: [0, 1.5, 0], children: [_jsx("cylinderGeometry", { args: [0.06, 0.07, 2.5, 12] }), _jsx("meshStandardMaterial", { color: "#16161a", roughness: 0.4, metalness: 0.7 })] }), _jsxs("mesh", { position: [0, 2.75, 0], castShadow: true, children: [_jsx("sphereGeometry", { args: [0.13, 16, 12] }), _jsx("meshStandardMaterial", { color: "#16161a", roughness: 0.3, metalness: 0.8 })] }), _jsx("group", { position: [0, 2.75, 0], rotation: [0, 0, -Math.PI / 4], children: _jsxs("mesh", { castShadow: true, position: [LAMP.ARM_LENGTH / 2, 0, 0], rotation: [0, 0, Math.PI / 2], children: [_jsx("cylinderGeometry", { args: [0.05, 0.05, LAMP.ARM_LENGTH, 12] }), _jsx("meshStandardMaterial", { color: "#16161a", roughness: 0.4, metalness: 0.7 })] }) }), _jsxs("group", { position: [1.55, LAMP.HEAD_HEIGHT, 0], rotation: [0, 0, -Math.PI / 2.6], children: [_jsxs("mesh", { castShadow: true, children: [_jsx("coneGeometry", { args: [0.6, 0.85, 18, 1, true] }), _jsx("meshStandardMaterial", { color: "#1a1a22", roughness: 0.4, metalness: 0.7, side: 2 })] }), _jsxs("mesh", { position: [0, -0.28, 0], children: [_jsx("sphereGeometry", { args: [0.28, 16, 12] }), _jsx("meshStandardMaterial", { color: LAMP.WARM, emissive: LAMP.WARM, emissiveIntensity: 2.6, toneMapped: false })] })] }), _jsx("primitive", { object: target.current, position: [5, -8, 5] }), _jsx("spotLight", { position: [1.55, LAMP.HEAD_HEIGHT, 0], target: target.current, intensity: LAMP.CONE_INTENSITY, distance: LAMP.CONE_DISTANCE, angle: LAMP.CONE_ANGLE, penumbra: LAMP.CONE_PENUMBRA, color: LAMP.WARM, castShadow: true, "shadow-mapSize-width": 2048, "shadow-mapSize-height": 2048 })] }));
}
